apiVersion: v1
kind: ConfigMap
metadata:
  name: task-config
  namespace: kiii-task-manager
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: todotraverse
  DB_USER: postgres
  POSTGRES_DB: todotraverse
  POSTGRES_USER: postgres